signatures = [
    {
        "extension": "3g2",
        "hex": "66 74 79 70 33 67",
        "offset": "4",
        "description": "3GPP2 multimedia files",
    },
    {
        "extension": "3gp",
        "hex": "66 74 79 70 33 67",
        "offset": "4",
        "description": "3rd Generation Partnership Project3GPP",
    },
    {
        "extension": "7z",
        "hex": "37 7A BC AF 27 1C",
        "offset": "0",
        "description": "7-Zip File Format",
    },
    {
        "extension": "8sv",
        "hex": "46 4F 52 4D NN NN NN NN 38 53 56 58",
        "offset": "0",
        "description": "IFF8-Bit Sampled Voice",
    },
    {
        "extension": "8svx",
        "hex": "46 4F 52 4D NN NN NN NN 38 53 56 58",
        "offset": "0",
        "description": "IFF8-Bit Sampled Voice",
    },
    {
        "extension": "DBA",
        "hex": "BE BA FE CA",
        "offset": "0",
        "description": "Palm Desktop Calendar Archive",
    },
    {
        "extension": "DBA",
        "hex": "00 01 42 44",
        "offset": "0",
        "description": "Palm Desktop To Do Archive",
    },
    {
        "extension": "MLV",
        "hex": "4D 4C 56 49",
        "offset": "0",
        "description": "Magic Lantern Video file",
    },
    {
        "extension": "PDB",
        "hex": "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
        "offset": "11",
        "description": "PalmPilot Database/Document File",
    },
    {
        "extension": "PIC",
        "hex": "00 NN",
        "offset": "0",
        "description": "IBM Storyboard bitmap file",
    },
    {
        "extension": "PIF",
        "hex": "00 NN",
        "offset": "0",
        "description": "WindowsProgram Information File",
    },
    {
        "extension": "SEA",
        "hex": "00 NN",
        "offset": "0",
        "description": "MacStuffit Self-Extracting Archive",
    },
    {
        "extension": "TDA",
        "hex": "00 01 44 54",
        "offset": "0",
        "description": "Palm Desktop Calendar Archive",
    },
    {
        "extension": "XML",
        "hex": "3c 3f 78 6d 6c 20",
        "offset": "0",
        "description": "eXtensible Markup Language when using theASCII character encoding",
    },
    {
        "extension": "YTR",
        "hex": "00 NN",
        "offset": "0",
        "description": "IRISOCR data file",
    },
    {
        "extension": "djv",
        "hex": "41 54 26 54 46 4F 52 4D NN NN NN NN 44 4A 56",
        "offset": "0",
        "description": "DjVu document. The following byte is either55 (U) for single-page or4D (M) for multi-page documents.",
    },
    {
        "extension": "acbm",
        "hex": "46 4F 52 4D NN NN NN NN 41 43 42 4D",
        "offset": "0",
        "description": "Amiga Contiguous Bitmap",
    },
    {
        "extension": "aif",
        "hex": "46 4F 52 4D NN NN NN NN 41 49 46 46",
        "offset": "0",
        "description": "Audio Interchange File Format",
    },
    {
        "extension": "aifc",
        "hex": "46 4F 52 4D NN NN NN NN 41 49 46 46",
        "offset": "0",
        "description": "Audio Interchange File Format",
    },
    {
        "extension": "aiff",
        "hex": "46 4F 52 4D NN NN NN NN 41 49 46 46",
        "offset": "0",
        "description": "Audio Interchange File Format",
    },
    {
        "extension": "anbm",
        "hex": "46 4F 52 4D NN NN NN NN 41 4E 42 4D",
        "offset": "0",
        "description": "IFFAnimated Bitmap",
    },
    {
        "extension": "anim",
        "hex": "46 4F 52 4D NN NN NN NN 41 4E 49 4D",
        "offset": "0",
        "description": "IFFCEL Animation",
    },
    {
        "extension": "apk",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "apk",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "apk",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "asf",
        "hex": "30 26 B2 75 8E 66 CF 11 A6 D9 00 AA 00 62 CE 6C",
        "offset": "0",
        "description": "Advanced Systems Format",
    },
    {
        "extension": "avi",
        "hex": "52 49 46 46 NN NN NN NN 41 56 49 20",
        "offset": "0",
        "description": "Audio Video Interleave video format",
    },
    {
        "extension": "bac",
        "hex": "42 41 43 4B 4D 49 4B 45 44 49 53 4B",
        "offset": "0",
        "description": "File ortape containing abackup done withAmiBack on an Amiga. It typically is paired with an index file (idx) with the table of contents.",
    },
    {
        "extension": "bin",
        "hex": "53 50 30 31",
        "offset": "0",
        "description": "Amazon Kindle Update Package",
    },
    {
        "extension": "bmp",
        "hex": "42 4D",
        "offset": "0",
        "description": "BMP file, abitmap format used mostly in theWindows world",
    },
    {
        "extension": "bmp",
        "hex": "42 4D",
        "offset": "0",
        "description": "BMP file, abitmap format used mostly in theWindows world",
    },
    {
        "extension": "bpg",
        "hex": "42 50 47 FB",
        "offset": "0",
        "description": "Better Portable Graphics format",
    },
    {
        "extension": "bz2",
        "hex": "42 5A 68",
        "offset": "0",
        "description": "Compressed file usingBzip2 algorithm",
    },
    {
        "extension": "cab",
        "hex": "4D 53 43 46",
        "offset": "0",
        "description": "Microsoft Cabinet file",
    },
    {
        "extension": "cin",
        "hex": "80 2A 5F D7",
        "offset": "0",
        "description": "KodakCineon image",
    },
    {
        "extension": "class",
        "hex": "CA FE BA BE",
        "offset": "0",
        "description": "Java class file,Mach-O Fat Binary",
    },
    {
        "extension": "cmus",
        "hex": "46 4F 52 4D NN NN NN NN 43 4D 55 53",
        "offset": "0",
        "description": "IFFMusical Score",
    },
    {
        "extension": "cr2",
        "hex": "49 49 2A 00 10 00 00 00 43 52",
        "offset": "0",
        "description": "Canon's RAW format is based on the TIFF file format",
    },
    {
        "extension": "cr2",
        "hex": "49 49 2A 00 10 00 00 00 43 52",
        "offset": "0",
        "description": "Canon RAW Format Version 2",
    },
    {
        "extension": "crx",
        "hex": "43 72 32 34",
        "offset": "0",
        "description": "Google Chrome extensionor packaged app",
    },
    {
        "extension": "cwk",
        "hex": "05 07 00 00 42 4F 42 4F 05 07 00 00 00 00 00 00 00 00 00 00 00 01",
        "offset": "0",
        "description": "AppleWorks 5 document",
    },
    {
        "extension": "cwk",
        "hex": "06 07 E1 00 42 4F 42 4F 06 07 E1 00 00 00 00 00 00 00 00 00 00 01",
        "offset": "0",
        "description": "AppleWorks 6 document",
    },
    {
        "extension": "dat",
        "hex": "50 4D 4F 43 43 4D 4F 43",
        "offset": "0",
        "description": "Windows Files And Settings Transfer Repository, See also USMT 3.0 (Win XP) and USMT 4.0 (Win 7) User Guides",
    },
    {
        "extension": "dcm",
        "hex": "44 49 43 4D",
        "offset": "128",
        "description": "DICOM Medical File Format",
    },
    {
        "extension": "deb",
        "hex": "21 3C 61 72 63 68 3E",
        "offset": "0",
        "description": "linux deb file",
    },
    {
        "extension": "der",
        "hex": "30 82",
        "offset": "0",
        "description": "DER encoded X.509 certificate",
    },
    {
        "extension": "dex",
        "hex": "64 65 78 0A 30 33 35 00",
        "offset": "0",
        "description": "Dalvik Executable",
    },
    {
        "extension": "dib",
        "hex": "42 4D",
        "offset": "0",
        "description": "BMP file, abitmap format used mostly in theWindows world",
    },
    {
        "extension": "dib",
        "hex": "42 4D",
        "offset": "0",
        "description": "BMP file, abitmap format used mostly in theWindows world",
    },
    {
        "extension": "djv",
        "hex": "41 54 26 54 46 4F 52 4D NN NN NN NN 44 4A 56",
        "offset": "0",
        "description": "DjVu document. The following byte is either55 (U) for single-page or4D (M) for multi-page documents.",
    },
    {
        "extension": "djvu",
        "hex": "41 54 26 54 46 4F 52 4D NN NN NN NN 44 4A 56",
        "offset": "0",
        "description": "DjVu document. The following byte is either55 (U) for single-page or4D (M) for multi-page documents.",
    },
    {
        "extension": "dmg",
        "hex": "78 01 73 0D 62 62 60",
        "offset": "0",
        "description": "Apple Disk Image file",
    },
    {
        "extension": "doc",
        "hex": "D0 CF 11 E0 A1 B1 1A E1",
        "offset": "0",
        "description": "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
    },
    {
        "extension": "docx",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "docx",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "docx",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "dpx",
        "hex": "53 44 50 58",
        "offset": "0",
        "description": "SMPTEDPX image (big endian format)",
    },
    {
        "extension": "dpx",
        "hex": "58 50 44 53",
        "offset": "0",
        "description": "SMPTEDPX image (little endian format)",
    },
    {
        "extension": "elf",
        "hex": "7F 45 4C 46",
        "offset": "0",
        "description": "Executable and Linkable Format",
    },
    {
        "extension": "exe",
        "hex": "4D 5A",
        "offset": "0",
        "description": "DOS MZ executable file format and its descendants (includingNE andPE)",
    },
    {
        "extension": "exr",
        "hex": "76 2F 31 01",
        "offset": "0",
        "description": "OpenEXR image",
    },
    {
        "extension": "faxx",
        "hex": "46 4F 52 4D NN NN NN NN 46 41 58 58",
        "offset": "0",
        "description": "IFFFacsimile Image",
    },
    {
        "extension": "faxx",
        "hex": "46 4F 52 4D NN NN NN NN 46 41 58 58",
        "offset": "0",
        "description": "IFFFacsimile Image",
    },
    {
        "extension": "fh8",
        "hex": "41 47 44 33",
        "offset": "0",
        "description": "FreeHand 8 document",
    },
    {
        "extension": "fits",
        "hex": "53 49 4D 50 4C 45 20 20 3D 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 54",
        "offset": "0",
        "description": "Flexible Image Transport System (FITS)",
    },
    {
        "extension": "flac",
        "hex": "66 4C 61 43",
        "offset": "0",
        "description": "Free Lossless Audio Codec",
    },
    {
        "extension": "flif",
        "hex": "46 4C 49 46",
        "offset": "0",
        "description": "Free Lossless Image Format",
    },
    {
        "extension": "ftxt",
        "hex": "46 4F 52 4D NN NN NN NN 46 54 58 54",
        "offset": "0",
        "description": "IFFFormatted Text",
    },
    {
        "extension": "gif",
        "hex": "47 49 46 38 39 61",
        "offset": "0",
        "description": "Image file encoded in theGraphics Interchange Format (GIF)",
    },
    {
        "extension": "gif",
        "hex": "47 49 46 38 39 61",
        "offset": "0",
        "description": "Image file encoded in theGraphics Interchange Format (GIF)",
    },

    {
        "extension": "gz",
        "hex": "1F 8B",
        "offset": "0",
        "description": "GZIP",
    },
    {
        "extension": "ibm",
        "hex": "46 4F 52 4D NN NN NN NN 49 4C 42 4D",
        "offset": "0",
        "description": "IFFInterleaved Bitmap Image",
    },
    {
        "extension": "ico",
        "hex": "00 00 01 00",
        "offset": "0",
        "description": "Computer icon encoded inICO file format",
    },
    {
        "extension": "idx",
        "hex": "49 4E 44 58",
        "offset": "0",
        "description": "Index file to a file ortape containing abackup done withAmiBack on anAmiga.",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 49 4C 42 4D",
        "offset": "0",
        "description": "IFFInterleaved Bitmap Image",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 38 53 56 58",
        "offset": "0",
        "description": "IFF8-Bit Sampled Voice",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 41 43 42 4D",
        "offset": "0",
        "description": "Amiga Contiguous Bitmap",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 41 4E 42 4D",
        "offset": "0",
        "description": "IFFAnimated Bitmap",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 41 4E 49 4D",
        "offset": "0",
        "description": "IFFCEL Animation",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 46 41 58 58",
        "offset": "0",
        "description": "IFFFacsimile Image",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 46 54 58 54",
        "offset": "0",
        "description": "IFFFormatted Text",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 53 4D 55 53",
        "offset": "0",
        "description": "IFFSimple Musical Score",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 43 4D 55 53",
        "offset": "0",
        "description": "IFFMusical Score",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 59 55 56 4E",
        "offset": "0",
        "description": "IFFYUV Image",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 46 41 4E 54",
        "offset": "0",
        "description": "AmigaFantavision Movie",
    },
    {
        "extension": "iff",
        "hex": "46 4F 52 4D NN NN NN NN 41 49 46 46",
        "offset": "0",
        "description": "Audio Interchange File Format",
    },
    {
        "extension": "ilbm",
        "hex": "46 4F 52 4D NN NN NN NN 49 4C 42 4D",
        "offset": "0",
        "description": "IFFInterleaved Bitmap Image",
    },
    {
        "extension": "jar",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "jar",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "jar",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "jpeg",
        "hex": "FF D8 FF DB",
        "offset": "0",
        "description": "JPEG raw or in theJFIF orExif file format",
    },
    {
        "extension": "jpeg",
        "hex": "FF D8 FF E0 NN NN 4A 46 49 46 00 01",
        "offset": "0",
        "description": "JPEG raw or in theJFIF orExif file format",
    },
    {
        "extension": "jpeg",
        "hex": "FF D8 FF E1 NN NN 45 78 69 66 00 00",
        "offset": "0",
        "description": "JPEG raw or in theJFIF orExif file format",
    },
    {
        "extension": "jpg",
        "hex": "FF D8 FF DB",
        "offset": "0",
        "description": "JPEG raw or in theJFIF orExif file format",
    },
    {
        "extension": "jpg",
        "hex": "FF D8 FF E0 NN NN 4A 46 49 46 00 01",
        "offset": "0",
        "description": "JPEG raw or in theJFIF orExif file format",
    },
    {
        "extension": "jpg",
        "hex": "FF D8 FF E1 NN NN 45 78 69 66 00 00",
        "offset": "0",
        "description": "JPEG raw or in theJFIF orExif file format",
    },
    {
        "extension": "lbm",
        "hex": "46 4F 52 4D NN NN NN NN 49 4C 42 4D",
        "offset": "0",
        "description": "IFFInterleaved Bitmap Image",
    },
    {
        "extension": "lep",
        "hex": "cf 84 01",
        "offset": "0",
        "description": "Lepton compressed JPEG image",
    },
    {
        "extension": "lz",
        "hex": "4C 5A 49 50",
        "offset": "0",
        "description": "lzip compressed file",
    },
    {
        "extension": "lz4",
        "hex": "04 22 4D 18",
        "offset": "0",
        "description": "LZ4 Frame Format, LZ4 block format does not offer any magic bytes.",
    },
    {
        "extension": "mid",
        "hex": "4D 54 68 64",
        "offset": "0",
        "description": "MIDI sound file",
    },
    {
        "extension": "midi",
        "hex": "4D 54 68 64",
        "offset": "0",
        "description": "MIDI sound file",
    },
    {
        "extension": "mk3d",
        "hex": "1A 45 DF A3",
        "offset": "0",
        "description": "Matroska media container, includingWebM",
    },
    {
        "extension": "mka",
        "hex": "1A 45 DF A3",
        "offset": "0",
        "description": "Matroska media container, includingWebM",
    },
    {
        "extension": "mks",
        "hex": "1A 45 DF A3",
        "offset": "0",
        "description": "Matroska media container, includingWebM",
    },
    {
        "extension": "mkv",
        "hex": "1A 45 DF A3",
        "offset": "0",
        "description": "Matroska media container, includingWebM",
    },
    {
        "extension": "mp3",
        "hex": "FF FB",
        "offset": "0",
        "description": "MPEG-1 Layer 3 file without anID3 tag or with anID3v1 tag (which's appended at the end of the file)",
    },
    {
        "extension": "mp3",
        "hex": "49 44 33",
        "offset": "0",
        "description": "MP3 file with an ID3v2 container",
    },
    {
        "extension": "mp4",
        "hex": "66 74 79 70 69 73 6F 6D",
        "offset": "4",
        "description": "MPEG-4 ISO Base Media file",
    },
    {
        "extension": "msg",
        "hex": "D0 CF 11 E0 A1 B1 1A E1",
        "offset": "0",
        "description": "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
    },
    {
        "extension": "mus",
        "hex": "46 4F 52 4D NN NN NN NN 53 4D 55 53",
        "offset": "0",
        "description": "IFFSimple Musical Score",
    },
    {
        "extension": "mus",
        "hex": "46 4F 52 4D NN NN NN NN 43 4D 55 53",
        "offset": "0",
        "description": "IFFMusical Score",
    },
    {
        "extension": "nes",
        "hex": "4E 45 53 1A",
        "offset": "0",
        "description": "Nintendo Entertainment System ROM file",
    },
    {
        "extension": "odp",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "odp",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "odp",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "ods",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "ods",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "ods",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "odt",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "odt",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "odt",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "oga",
        "hex": "4F 67 67 53",
        "offset": "0",
        "description": "Ogg, anopen source media container format",
    },
    {
        "extension": "ogg",
        "hex": "4F 67 67 53",
        "offset": "0",
        "description": "Ogg, anopen source media container format",
    },
    {
        "extension": "ogv",
        "hex": "4F 67 67 53",
        "offset": "0",
        "description": "Ogg, anopen source media container format",
    },
    {
        "extension": "pdb",
        "hex": "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
        "offset": "11",
        "description": "PalmPilot Database/Document File",
    },
    {
        "extension": "pdf",
        "hex": "25 50 44 46",
        "offset": "0",
        "description": "PDF document",
    },
    {
        "extension": "png",
        "hex": "89 50 4E 47 0D 0A 1A 0A",
        "offset": "0",
        "description": "Image encoded in thePortable Network Graphics format",
    },
    {
        "extension": "ppt",
        "hex": "D0 CF 11 E0 A1 B1 1A E1",
        "offset": "0",
        "description": "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
    },
    {
        "extension": "pptx",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "pptx",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "pptx",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "ps",
        "hex": "25 21 50 53",
        "offset": "0",
        "description": "PostScript document",
    },
    {
        "extension": "psd",
        "hex": "38 42 50 53",
        "offset": "0",
        "description": "Photoshop Document file,Adobe Photoshop's native file format",
    },
    {
        "extension": "rar",
        "hex": "52 61 72 21 1A 07 00",
        "offset": "0",
        "description": "RAR archive version 1.50 onwards",
    },
    {
        "extension": "rar",
        "hex": "52 61 72 21 1A 07 01 00",
        "offset": "0",
        "description": "RAR archive version 5.0 onwards",
    },
    {
        "extension": "rpm",
        "hex": "ed ab ee db",
        "offset": "0",
        "description": "RedHat Package Manager (RPM) package",
    },
    {
        "extension": "smu",
        "hex": "46 4F 52 4D NN NN NN NN 53 4D 55 53",
        "offset": "0",
        "description": "IFFSimple Musical Score",
    },
    {
        "extension": "smus",
        "hex": "46 4F 52 4D NN NN NN NN 53 4D 55 53",
        "offset": "0",
        "description": "IFFSimple Musical Score",
    },
    {
        "extension": "snd",
        "hex": "46 4F 52 4D NN NN NN NN 38 53 56 58",
        "offset": "0",
        "description": "IFF8-Bit Sampled Voice",
    },
    {
        "extension": "snd",
        "hex": "46 4F 52 4D NN NN NN NN 41 49 46 46",
        "offset": "0",
        "description": "Audio Interchange File Format",
    },
    {
        "extension": "stg",
        "hex": "4D 49 4C 20",
        "offset": "0",
        "description": "'SEAN: Session Analysis' Training file. Also used in compatible software 'Rpw: Rowperfect for Windows' and 'RP3W: ROWPERFECT3 for Windows'.",
    },
    {
        "extension": "svx",
        "hex": "46 4F 52 4D NN NN NN NN 38 53 56 58",
        "offset": "0",
        "description": "IFF8-Bit Sampled Voice",
    },
    {
        "extension": "swf",
        "hex": "43 57 53",
        "offset": "0",
        "description": "flash .swf",
    },
    {
        "extension": "swf",
        "hex": "46 57 53",
        "offset": "0",
        "description": "flash .swf",
    },
    {
        "extension": "tar",
        "hex": "75 73 74 61 72 00 30 30 75 73 74 61 72 20 20 00",
        "offset": "257",
        "description": "tar archive",
    },
    {
        "extension": "tar.gz",
        "hex": "1F 8B",
        "offset": "0",
        "description": "GZIP",
    },
    {
        "extension": "tar.z",
        "hex": "1F 9D",
        "offset": "0",
        "description": "usingLempel-Ziv-Welch algorithm",
    },
    {
        "extension": "tar.z",
        "hex": "1F A0",
        "offset": "0",
        "description": "usingLZH algorithm",
    },
    {
        "extension": "tif",
        "hex": "49 49 2A 00",
        "offset": "0",
        "description": "Tagged Image File Format (little endian format)",
    },
    {
        "extension": "tif",
        "hex": "4D 4D 00 2A",
        "offset": "0",
        "description": "Tagged Image File Format (big endian format)",
    },
    {
        "extension": "tiff",
        "hex": "49 49 2A 00",
        "offset": "0",
        "description": "Tagged Image File Format (little endian format)",
    },
    {
        "extension": "tiff",
        "hex": "4D 4D 00 2A",
        "offset": "0",
        "description": "Tagged Image File Format (big endian format)",
    },
    {
        "extension": "toast",
        "hex": "45 52 02 00 00 00 8B 45 52 02 00 00 00",
        "offset": "0",
        "description": "RoxioToast disc image file, also some .dmg-files begin with same bytes",
    },
    {
        "extension": "tox",
        "hex": "74 6F 78 33",
        "offset": "0",
        "description": "Open source portable voxel file",
    },
    {
        "extension": "txt",
        "hex": "46 4F 52 4D NN NN NN NN 46 54 58 54",
        "offset": "0",
        "description": "IFFFormatted Text",
    },
    {
        "extension": "vmdk",
        "hex": "4B 44 4D",
        "offset": "0",
        "description": "VMDK files",
    },
    {
        "extension": "vsdx",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "vsdx",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "vsdx",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "wasm",
        "hex": "6d 73 61 00",
        "offset": "0",
        "description": "WebAssembly binary format",
    },
    {
        "extension": "wav",
        "hex": "52 49 46 46 NN NN NN NN 57 41 56 45",
        "offset": "0",
        "description": "Waveform Audio File Format",
    },
    {
        "extension": "webm",
        "hex": "1A 45 DF A3",
        "offset": "0",
        "description": "Matroska media container, includingWebM",
    },
    {
        "extension": "webp",
        "hex": "52 49 46 46 NN NN NN NN",
        "offset": "0",
        "description": "Google WebP image file",
    },
    {
        "extension": "wma",
        "hex": "30 26 B2 75 8E 66 CF 11 A6 D9 00 AA 00 62 CE 6C",
        "offset": "0",
        "description": "Advanced Systems Format",
    },
    {
        "extension": "wmv",
        "hex": "30 26 B2 75 8E 66 CF 11 A6 D9 00 AA 00 62 CE 6C",
        "offset": "0",
        "description": "Advanced Systems Format",
    },
    {
        "extension": "woff",
        "hex": "77 4F 46 46",
        "offset": "0",
        "description": "WOFF File Format 1.0",
    },
    {
        "extension": "woff2",
        "hex": "77 4F 46 32",
        "offset": "0",
        "description": "WOFF File Format 2.0",
    },
    {
        "extension": "xar",
        "hex": "78 61 72 21",
        "offset": "0",
        "description": "eXtensible Archive format",
    },
    {
        "extension": "xls",
        "hex": "D0 CF 11 E0 A1 B1 1A E1",
        "offset": "0",
        "description": "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
    },
    {
        "extension": "xlsx",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "xlsx",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "xlsx",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "yuv",
        "hex": "46 4F 52 4D NN NN NN NN 59 55 56 4E",
        "offset": "0",
        "description": "IFFYUV Image",
    },
    {
        "extension": "yuvn",
        "hex": "46 4F 52 4D NN NN NN NN 59 55 56 4E",
        "offset": "0",
        "description": "IFFYUV Image",
    },
    {
        "extension": "z",
        "hex": "1F 9D",
        "offset": "0",
        "description": "compressed file (often tar zip)",
    },
    {
        "extension": "z",
        "hex": "1F A0",
        "offset": "0",
        "description": "Compressed file (often tar zip)",
    },
    {
        "extension": "zip",
        "hex": "50 4B 03 04",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML",
    },
    {
        "extension": "zip",
        "hex": "50 4B 05 06",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
    },
    {
        "extension": "zip",
        "hex": "50 4B 07 08",
        "offset": "0",
        "description": "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
    },
    {
        "extension": "dcm",
        "hex": "44 49 43 4D",
        "offset": "0x80",
        "description": "DICOM Medical File Format",
    },
    {
        "extension": "iso",
        "hex": "43 44 30 30 31",
        "offset": "0x8001",
        "description": "ISO9660 CD/DVD image file",
    },
    {
        "extension": "iso",
        "hex": "43 44 30 30 31",
        "offset": "0x8801",
        "description": "ISO9660 CD/DVD image file",
    },
    {
        "extension": "iso",
        "hex": "43 44 30 30 31",
        "offset": "0x9001",
        "description": "ISO9660 CD/DVD image file",
    },
    {
        "extension": "tar",
        "hex": "75 73 74 61 72 00 30 30 75 73 74 61 72 20 20 00",
        "offset": "0x101",
        "description": "tar archive",
    },
]
